name: pull request
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: set repo name
        shell: bash
        run: |
          echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download operator sdk
        shell: bash
        env:
          RELEASE_VERSION: v1.9.0
        run: |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk_linux_amd64
          chmod +x operator-sdk_linux_amd64
          mkdir ${HOME}/bin
          mv operator-sdk_linux_amd64 ${HOME}/bin/operator-sdk
          echo "${HOME}/bin" >> $GITHUB_PATH

      - name: build bundle
        shell: bash
        run: make bundle IMG=quay.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):0.0.1 VERSION=0.0.1 DEFAULT_CHANNEL=alpha

      - name: verify bundle
        shell: bash
        run: operator-sdk bundle validate ./bundle --select-optional name=operatorhub

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: "Build Operator Image"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: false
          tags: "ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:v0.0.1"

      - name: "Build Bundle Image"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bundle.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: false
          tags: "ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}-bundle:0.0.1"
